import Head from "next/head";
import FAQ from "./FAQ";
import Link from "next/link";

const staticMapUrl = "https://via.placeholder.com/";
const logoUrls = [
  "https://via.placeholder.com/150x150?text=Logo%201",
  "https://via.placeholder.com/150x150?text=Logo%202",
  "https://via.placeholder.com/150x150?text=Logo%203",
  "https://via.placeholder.com/150x150?text=Logo%204",
  "https://via.placeholder.com/150x150?text=Logo%205",
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-blue-100 mx-auto pb-10">
        <div className="container mx-auto px-4 sm:px-8 md:px-20 py-4">
          <nav className="text-blue-900 text-lg font-medium flex justify-between w-2/5 sm:w-1/2">
            <Link href="/" className="underline">
              HOME
            </Link>{" "}
            &gt;{" "}
            <Link href="/" className="underline">
              OFFER
            </Link>{" "}
            &gt;{" "}
            <Link href="/" className="underline">
              ILLINOIS
            </Link>{" "}
            &gt; CHICAGO
          </nav>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="py-4">
              <h2 className="text-3xl sm:text-4xl md:text-5xl text-blue-800 font-bold">
                SwiftHomes
              </h2>
              <p className="text-blue-800 my-4">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-5 gap-2">
                <div className="sm:col-span-3">
                  <div className="bg-blue-900 p-4 rounded-lg">
                    <p className="text-lg text-white">Accredited Business</p>
                  </div>
                </div>
                <div className="sm:col-span-2">
                  <div className="bg-blue-900 p-4 rounded-lg ">
                    <p className="text-lg text-white">Our Score: 9.5</p>
                  </div>
                </div>
              </div>
              <div className="bg-white p-4 rounded-lg my-4">
                <p className="text-base sm:text-lg md:text-xl/loose">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Doloribus, repellendus distinctio, accusantium natus
                  voluptatem explicabo dolorem culpa illum debitis fugit vel
                  provident minus placeat odit possimus totam impedit excepturi
                  doloremque!
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div className="col-span-1">
                  <button className="w-full h-14 bg-blue-500 hover:bg-blue-600 text-white font-bold rounded">
                    Get A Quote
                  </button>
                </div>
                <div className="col-span-1 py-3 pl-2">
                  <Link
                    href="#"
                    className="text-blue-800 text-lg font-medium flex items-center"
                  >
                    See More Roffers!{" "}
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      className="w-6 inline-block ml-1"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M9 5l7 7-7 7"
                      />
                    </svg>
                  </Link>
                </div>
              </div>
            </div>
            <div className="bg-white p-4  rounded-lg">
              <img
                src={staticMapUrl + "520x450"}
                alt="Static Map"
                className="w-full md:w-auto"
              />
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 my-6 md:px-44">
          <div className="bg-white rounded-lg shadow-xl p-4">
            <div className="bg-blue-500 text-white rounded-lg">
              <h2 className="text-xl sm:text-2xl md:text-3xl font-semibold p-3 text-center">
                Pros
              </h2>
            </div>
            <ul className="list-disc list-inside my-6">
              <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
              <li>Phasellus in nunc sed justo tincidunt vehicula.</li>
              <li>Proin non nisl nec justo posuere vehicula.</li>
              <li>Proin non nisl nec justo posuere vehicula.</li>
              <li>Proin non nisl nec justo posuere vehicula.</li>
            </ul>
          </div>
          <div className="bg-white rounded-lg shadow-xl p-4">
            <div className="bg-blue-500 text-white p-3 rounded-lg">
              <h2 className="text-xl sm:text-2xl md:text-3xl font-semibold text-center">
                Cons
              </h2>
            </div>
            <ul className="list-disc list-inside my-6">
              <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
              <li>Phasellus in nunc sed justo tincidunt vehicula.</li>
              <li>Proin non nisl nec justo posuere vehicula.</li>
            </ul>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-xl p-8 md:mx-44 ">
          <div className="w-full sm:w-1/2 mx-auto bg-blue-500 text-white p-3 rounded-lg">
            <h2 className="text-xl sm:text-2xl md:text-3xl font-semibold text-center">
              Authoritiyst Verdict
            </h2>
          </div>
          <ul className="list-disc list-inside my-6">
            <li>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus
              in nunc sed justo tincidunt vehicula.
            </li>
            <li>
              Phasellus in nunc sed justo tincidunt vehicula. Phasellus in nunc
              sed justo tincidunt vehicula.
            </li>
            <li>
              Proin non nisl nec justo posuere vehicula. Phasellus in nunc sed
              justo tincidunt vehicula.
            </li>
          </ul>
          <div className="flex justify-center items-center">
            <button className="bg-blue-500 hover:bg-blue-600 text-white font-semibold w-1/2 sm:w-1/5 p-3 rounded-lg">
              Get A Quote
            </button>
          </div>
        </div>
      </div>
      <div className="bg-blue-800 text-white px-4 py-6 sm:px-36">
        <h1 className="text-2xl sm:text-3xl md:text-4xl font-semibold text-center">
          Authoritiyst Featured In:
        </h1>
        <div className="flex flex-wrap justify-center mt-6">
          {logoUrls.map((logoUrl, index) => (
            <div key={index} className="w-1/2 sm:w-1/4 md:w-1/5 lg:w-1/6 mb-4">
              <img
                src={logoUrl}
                alt={`Brand Logo ${index}`}
                className="mx-auto"
              />
            </div>
          ))}
        </div>
      </div>
      <div className="bg-white w-full my-10 md:px-44">
        <div className="bg-blue-500 text-white py-6 px-4 sm:px-10 rounded">
          <div className="container mx-auto flex flex-col-reverse sm:flex-row justify-between items-center">
            <div className="w-full sm:w-1/2 p-6">
              <h2 className="text-lg sm:text-lg md:text-xl font-semibold mb-4">
                Discover the Authoriyist Score
              </h2>
              <p className="text-lg sm:text-sm md:text-lg mb-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
                nec est feugiat, auctor lorem in, consequat velit.
              </p>
              <button className="bg-white hover:bg-blue-950 text-blue-500 font-semibold py-2 px-4 rounded">
                Get Free Quote
              </button>
            </div>
            <div className="w-full sm:w-1/2 bg-cover bg-center bg-no-repeat h-80">
              <img
                src={staticMapUrl + "600x350"}
                alt="Description of the image"
                className="object-cover max-w-full h-auto"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="bg-blue-900 text-white py-4">
        <div className="container mx-auto text-center">
          <h1 className="text-2xl py-10 sm:text-3xl text-center font-semibold">
            See the Top Services Provided in your Area
          </h1>
          <div className="overflow-x-auto px-16">
            <table className="min-w-full border-collapse border border-blue-300 bg-white">
              <thead>
                <tr className="bg-blue-300 text-blue-900">
                  <th className="border-b-2 border-blue-300 py-2 px-4">
                    Business
                  </th>
                  <th className="border-b-2 border-blue-300 py-2 px-4"></th>
                  <th className="border-b-2 border-blue-300 py-2 px-4">
                    Summaries
                  </th>
                  <th className="border-b-2 border-blue-300 py-2 px-4">
                    Score
                  </th>
                  <th className="border-b-2 border-blue-300 py-2 px-4">
                    Get Quote
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border-b-8 border-r-2 border-blue-300 py-10">
                    <img
                      src={logoUrls[0]}
                      alt="Logo 1"
                      className="mx-auto"
                      style={{
                        width: "100%",
                        maxWidth: "150px",
                        height: "auto",
                      }}
                    />
                  </td>
                  <td className="border-b-8 border-r-2 border-blue-300 px-4 py-20">
                    Cell 1-2
                  </td>
                  <td className="border-b-8 border-r-2 border-blue-300 px-4 py-20">
                    Cell 1-3
                  </td>
                  <td className="border-b-8 border-r-2 border-blue-300 px-4 py-20">
                    Cell 1-4
                  </td>
                  <td className="border-b-8 border-blue-300 text-center">
                    <button className="bg-blue-500 hover:bg-blue-600 text-white font-semibold w-2/3 sm:w-2/3 p-3 rounded-lg">
                      Get A Quote
                    </button>
                  </td>
                </tr>
                <tr>
                  <td className="border-b-8 border-r-2 border-blue-300 py-10">
                    <img
                      src={logoUrls[1]}
                      alt="Logo 2"
                      className="mx-auto"
                      style={{
                        width: "100%",
                        maxWidth: "150px",
                        height: "auto",
                      }}
                    />
                  </td>
                  <td className="border-b-8 border-r-2 border-blue-300 ">
                    Cell 2-2
                  </td>
                  <td className="border-b-8 border-r-2 border-blue-300 ">
                    Cell 2-3
                  </td>
                  <td className="border-b-8 border-r-2 border-blue-300 ">
                    Cell 2-4
                  </td>
                  <td className="border-b-8 border-blue-300 text-center">
                    <button className="bg-blue-500 hover:bg-blue-600  text-white font-semibold w-2/3 sm:w-2/3 p-3 rounded-lg">
                      Get A Quote
                    </button>
                  </td>
                </tr>
                {/* Repeat for each row */}
              </tbody>
            </table>
            <button className="bg-blue-500 hover:bg-blue-600 text-white font-semibold w-1/2 sm:w-1/5 p-3 my-12 rounded-lg">
              Chat an Expert
            </button>
          </div>
        </div>
      </div>
      <div className="bg-white mx-auto md:px-44 my-16">
        <div className="flex justify-between items-center mb-4">
          <h1 className="text-blue-900 text-2xl font-semibold">
            Articles about Roofing
          </h1>
          <a href="#" className="text-blue-400 font-semibold">
            See More Articles
          </a>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
          <div className="bg-white rounded-lg shadow-xl overflow-hidden transition-transform transform hover:scale-105">
            <div className="relative h-64">
              <img
                src={staticMapUrl + "520x450"}
                alt="Card Image"
                className="object-cover w-full h-full"
              />
            </div>
            <div className="text-blue-900 bg-white p-3">
              <h2 className="text-xl font-bold my-5">Your Card Title</h2>
              <p className="text-blue-400 font-semibold">Date</p>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-xl overflow-hidden transition-transform transform hover:scale-105">
            <div className="relative h-64">
              <img
                src={staticMapUrl + "520x450"}
                alt="Card Image"
                className="object-cover w-full h-full"
              />
            </div>
            <div className="text-blue-900 bg-white p-3">
              <h2 className="text-xl font-bold my-5">Your Card Title</h2>
              <p className="text-blue-400 font-semibold">Date</p>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-xl overflow-hidden transition-transform transform hover:scale-105">
            <div className="relative h-64">
              <img
                src={staticMapUrl + "520x450"}
                alt="Card Image"
                className="object-cover w-full h-full"
              />
            </div>
            <div className="text-blue-900 bg-white p-3">
              <h2 className="text-xl font-bold my-5">Your Card Title</h2>
              <p className="text-blue-400 font-semibold">Date</p>
            </div>
          </div>
        </div>
      </div>
      <FAQ />
    </>
  );
}
